# Generated by Django 4.1 on 2022-08-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product", new_name="catagory",
        ),
    ]
