# Generated by Django 4.1 on 2022-10-26 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_catagory_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
