# Generated by Django 4.1 on 2022-08-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "MALE"), ("Female", "FEMALE"), ("Other", "OTHER")],
                default="",
                max_length=6,
            ),
        ),
    ]
