# Generated by Django 4.1 on 2022-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                default="",
                max_length=6,
            ),
        ),
    ]
