# Generated by Django 4.1 on 2022-09-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_alter_address_apartment_no_alter_address_floor_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
