# Generated by Django 4.1 on 2022-09-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0008_alter_address_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="floor_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
