# Generated by Django 4.1 on 2022-11-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0014_alter_address_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="floor_no",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
