# Generated by Django 4.1 on 2022-10-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_orderitem_price_orderitem_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="order",),
        migrations.DeleteModel(name="order",),
    ]
