# Generated by Django 4.1 on 2022-10-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_orderitem_order_delete_order"),
    ]

    operations = [
        migrations.DeleteModel(name="Cart",),
    ]
