# Generated by Django 4.1 on 2022-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_delete_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
