# Generated by Django 4.1 on 2022-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_orderitem_shipment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
