# Generated by Django 4.1 on 2022-10-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_rename_order_orderitem_addresss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="addresss", new_name="address",
        ),
    ]
