# Generated by Django 4.1 on 2022-10-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_rename_addresss_orderitem_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="delivery_date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="timeslot",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
